openapi: 3.0.3
info:
  title: Clients API
  version: 1.0.0
  description: 의뢰인 관리 CRUD API

paths:
  /clients:
    get:
      summary: 의뢰인 목록 조회
      description: 현재 로그인한 변호사의 의뢰인 목록을 조회한다
      tags: [Clients]
      security:
        - cookieAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: 이름, 전화번호, 이메일 검색
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: 의뢰인 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  clients:
                    type: array
                    items:
                      $ref: '#/components/schemas/Client'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: 의뢰인 추가
      tags: [Clients]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientCreate'
      responses:
        '201':
          description: 의뢰인 추가 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '400':
          $ref: '#/components/responses/BadRequest'

  /clients/{client_id}:
    get:
      summary: 의뢰인 상세 조회
      tags: [Clients]
      security:
        - cookieAuth: []
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 의뢰인 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: 의뢰인 정보 수정
      tags: [Clients]
      security:
        - cookieAuth: []
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientUpdate'
      responses:
        '200':
          description: 수정 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Client'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: 의뢰인 삭제
      tags: [Clients]
      security:
        - cookieAuth: []
      parameters:
        - name: client_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제 완료
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    ClientCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        phone:
          type: string
          pattern: '^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$'
        email:
          type: string
          format: email
        memo:
          type: string
      required:
        - name

    ClientUpdate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        phone:
          type: string
        email:
          type: string
          format: email
        memo:
          type: string

    Client:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        phone:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        memo:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - created_at
        - updated_at

  responses:
    Unauthorized:
      description: 인증되지 않음
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string

    Forbidden:
      description: 권한 없음 (lawyer 역할만 접근 가능)
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string

    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string

    NotFound:
      description: 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
