openapi: 3.0.3
info:
  title: Detectives API
  version: 1.0.0
  description: 탐정 관리 CRUD API

paths:
  /detectives:
    get:
      summary: 탐정 목록 조회
      description: 현재 로그인한 변호사의 탐정 목록을 조회한다
      tags: [Detectives]
      security:
        - cookieAuth: []
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: 이름, 전화번호, 이메일, 전문분야 검색
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: 탐정 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  detectives:
                    type: array
                    items:
                      $ref: '#/components/schemas/Detective'
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: 탐정 추가
      tags: [Detectives]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectiveCreate'
      responses:
        '201':
          description: 탐정 추가 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detective'
        '400':
          $ref: '#/components/responses/BadRequest'

  /detectives/{detective_id}:
    get:
      summary: 탐정 상세 조회
      tags: [Detectives]
      security:
        - cookieAuth: []
      parameters:
        - name: detective_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 탐정 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detective'
        '404':
          $ref: '#/components/responses/NotFound'

    put:
      summary: 탐정 정보 수정
      tags: [Detectives]
      security:
        - cookieAuth: []
      parameters:
        - name: detective_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectiveUpdate'
      responses:
        '200':
          description: 수정 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detective'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'

    delete:
      summary: 탐정 삭제
      tags: [Detectives]
      security:
        - cookieAuth: []
      parameters:
        - name: detective_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: 삭제 완료
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    DetectiveCreate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        phone:
          type: string
          pattern: '^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$'
        email:
          type: string
          format: email
        specialty:
          type: string
          maxLength: 100
          description: 전문 분야 (예: 불륜 조사, 자산 추적)
        memo:
          type: string
      required:
        - name

    DetectiveUpdate:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        phone:
          type: string
        email:
          type: string
          format: email
        specialty:
          type: string
          maxLength: 100
        memo:
          type: string

    Detective:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        phone:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        specialty:
          type: string
          nullable: true
        memo:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - created_at
        - updated_at

  responses:
    Unauthorized:
      description: 인증되지 않음
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string

    Forbidden:
      description: 권한 없음 (lawyer 역할만 접근 가능)
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string

    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string

    NotFound:
      description: 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
