openapi: 3.0.3
info:
  title: Notifications API
  version: 1.0.0
  description: 알림 조회 및 읽음 처리 API

paths:
  /notifications:
    get:
      summary: 알림 목록 조회
      description: 현재 사용자의 알림 목록을 조회한다
      tags: [Notifications]
      security:
        - cookieAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 10
            maximum: 50
          description: 조회할 알림 수
        - name: unread_only
          in: query
          schema:
            type: boolean
            default: false
          description: 읽지 않은 알림만 조회
      responses:
        '200':
          description: 알림 목록
          content:
            application/json:
              schema:
                type: object
                properties:
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
                  unread_count:
                    type: integer
        '401':
          $ref: '#/components/responses/Unauthorized'

  /notifications/{notification_id}/read:
    patch:
      summary: 알림 읽음 처리
      tags: [Notifications]
      security:
        - cookieAuth: []
      parameters:
        - name: notification_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: 읽음 처리 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '404':
          $ref: '#/components/responses/NotFound'

  /notifications/read-all:
    patch:
      summary: 모든 알림 읽음 처리
      tags: [Notifications]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 모든 알림 읽음 처리 완료
          content:
            application/json:
              schema:
                type: object
                properties:
                  updated_count:
                    type: integer

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [case_update, message, system]
        title:
          type: string
          maxLength: 100
        content:
          type: string
          maxLength: 500
        is_read:
          type: boolean
        related_id:
          type: string
          format: uuid
          nullable: true
        created_at:
          type: string
          format: date-time
      required:
        - id
        - type
        - title
        - content
        - is_read
        - created_at

  responses:
    Unauthorized:
      description: 인증되지 않음
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: Not authenticated

    NotFound:
      description: 리소스를 찾을 수 없음
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
                example: Notification not found
