openapi: 3.0.3
info:
  title: Detective Portal API
  description: |
    API for detective portal functionality (US11).
    Handles case assignment, evidence upload with EXIF, and earnings.
  version: 1.0.0

paths:
  /detective/cases:
    get:
      summary: List assigned cases
      description: |
        Get cases assigned to the authenticated detective.
        Only returns cases where user is a member.
      operationId: listDetectiveCases
      tags:
        - Detective Portal
      responses:
        '200':
          description: List of assigned cases
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CaseSummary'
        '403':
          description: Not a detective user

  /detective/evidence/{evidence_id}/exif:
    get:
      summary: Get EXIF metadata
      description: |
        Retrieve extracted EXIF metadata from uploaded image.
        Returns GPS coordinates and timestamp if available.
      operationId: getEvidenceExif
      tags:
        - Detective Portal
      parameters:
        - name: evidence_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: EXIF metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExifMetadata'
        '404':
          description: Evidence not found or no EXIF data

  /detective/earnings:
    get:
      summary: Get earnings summary
      description: |
        Get detective's earnings summary including total and per-case breakdown.
      operationId: getEarnings
      tags:
        - Detective Portal
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, paid, all]
          description: Filter by payment status
      responses:
        '200':
          description: Earnings data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarningsSummary'

  /detective/earnings/{earning_id}:
    get:
      summary: Get earning detail
      description: Get details of a specific earning record
      operationId: getEarningDetail
      tags:
        - Detective Portal
      parameters:
        - name: earning_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Earning detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EarningDetail'

components:
  schemas:
    CaseSummary:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        status:
          type: string
          enum: [open, in_progress, closed]
        assigned_at:
          type: string
          format: date-time
        evidence_count:
          type: integer

    ExifMetadata:
      type: object
      properties:
        evidence_id:
          type: string
          format: uuid
        gps_latitude:
          type: number
          format: double
          nullable: true
        gps_longitude:
          type: number
          format: double
          nullable: true
        gps_altitude:
          type: number
          nullable: true
        datetime_original:
          type: string
          format: date-time
          nullable: true
        camera_make:
          type: string
          nullable: true
        camera_model:
          type: string
          nullable: true
        has_location:
          type: boolean
          description: True if GPS coordinates are available

    EarningsSummary:
      type: object
      properties:
        total_earned:
          type: number
          format: decimal
        total_pending:
          type: number
          format: decimal
        total_paid:
          type: number
          format: decimal
        earnings:
          type: array
          items:
            $ref: '#/components/schemas/EarningDetail'

    EarningDetail:
      type: object
      properties:
        id:
          type: string
          format: uuid
        case_id:
          type: string
          format: uuid
        case_title:
          type: string
        amount:
          type: number
          format: decimal
        description:
          type: string
        status:
          type: string
          enum: [pending, paid]
        created_at:
          type: string
          format: date-time
        paid_at:
          type: string
          format: date-time
          nullable: true
